const Countries = {
  countriesList: [
    {name: 'Selected Country', code: 'XX'},
    {name: 'Argentina', code: 'AR'},
    {name: 'Australia', code: 'AU'},
    {name: 'Austria', code: 'AT'},
    {name: 'Belgium', code: 'BE'},
    {name: 'Canada', code: 'CA'},
    {name: 'China', code: 'CN'},
    {name: 'Egypt', code: 'EG'},
    {name: 'France', code: 'FR'},
    {name: 'Germany', code: 'DE'},
    {name: 'Hungary', code: 'HU'},
    {name: 'India', code: 'IN'},
    {name: 'Ireland', code: 'IE'},
    {name: 'Israel', code: 'IL'},
    {name: 'Italy', code: 'IT'},
    {name: 'Mexico', code: 'MX'},
    {name: 'Netherlands', code: 'NL'},
    {name: 'New Zealand', code: 'NZ'},
    {name: 'Norway', code: 'NO'},
    {name: 'Russian Federation', code: 'RU'},
    {name: 'Saudi Arabia', code: 'SA'},
    {name: 'Singapore', code: 'SG'},
    {name: 'South Africa', code: 'ZA'},
    {name: 'Sweden', code: 'SE'},
    {name: 'Switzerland', code: 'CH'},
    {name: 'Taiwan, Province of China', code: 'TW'},
    {name: 'Thailand', code: 'TH'},
    {name: 'Turkey', code: 'TR'},
    {name: 'Ukraine', code: 'UA'},
    {name: 'United Arab Emirates', code: 'AE'},
    {name: 'United Kingdom', code: 'GB'},
    {name: 'United States', code: 'US'},
  ],
};

export default Countries;
